# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d34b8eed76d46f004f545198a9786438bd6862b726de57a181bc35eba91ad4e07d04e34ea2e89f363df857ea54703f21523ed7bea1053cb3e245755893665a8a

test:
  secret_key_base: 2385d771e061f085687b69ea51c103450f73b631a6961c27e087af3700dde3b090456042e219366b2cf83cbec922bc3931f695fbea5b4df9567027f4c1de3dd9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
